main: com.worldgroup.coa.App
name: WorldGroupTp
version: 0.6
author: Coa
description: Extension to the worldpos plugin by mike724
commands:
  worldgrouptp:
    description: Teleports player to a worldgroup
    usage: /worldgrouptp <player> <worldgroup>
  createwg:
    description: Makes a new worldgroup
    usage: /createwg <name>
    permission: worldgrouptp.admin
  addworld:
    description: Adds world to worldgroup
    usage: /addworld <worldgroup> <world>
    permission: worldgrouptp.admin
  listwg:
    description: Lists all worldgroups
    usage: /listwg
    permission: worldgrouptp.admin
  deletewg:
    description: Deletes specified worldgroup
    usage: /deletewg <worldgroup>
    permission: worldgrouptp.admin